server:
  port: 2081
  context-path: /myspringboot

  tomcat:
    basedir: D:/yhfund-tomcat-tmp

logging:
  path: D:/yhfund-tomcat-tmp
  file: myapp.log


app:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@172.16.1.61:1521:tads
    username: yhapp1
    password: yhapp1
    driver-class-name: oracle.jdbc.driver.OracleDriver

weixin:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@172.16.1.30:1521:devdb
    username: yhwx
    password: yhwx
    driver-class-name: oracle.jdbc.driver.OracleDriver
